### ISSUE TITLE
Add (default) variables that can be used in any test step

### ISSUE THREAD

**Issue by walterchris** [BlindspotSoftware/contest-old#27]
# Add common variables 

The idea is to be able to define common variables that can be used within every test step. In the context of Secunet, these common variables can be used as defaults.

## Example

```
    TestFetcherFetchParameters:
      TestName: Boot CentOS coreboot
      Defaults:
        - name: context
          value: ["Something"]
        - name: IP
          value: ["192.168.0.24"]
        - name: host
          value: ["secunettest-ThinkPad-T14-Gen-3.lab.9e.network"]
      Steps:
        - name: qemu
          label: Qemu boot test.
          parameters:
            executable: ["{{default.context}}"]
            firmware: ["/tmp/firmware.bin"]
```

The idea is that these defaults can be used either implicitly within the test step, or explicitly within the test step description as shown above. It might be that we need to call it via `{{ default(host) }}`.

What do you think?
